CREATE TABLE [dbo].[FuncionarioServico] (
    [ServicoId]     UNIQUEIDENTIFIER NOT NULL,
    [FuncionarioId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_FUNACIONARIOSERVICO] PRIMARY KEY CLUSTERED ([ServicoId] ASC, [FuncionarioId] ASC),
    CONSTRAINT [FK_FUNACION_ASSOCIATI_FUNCINAR] FOREIGN KEY ([FuncionarioId]) REFERENCES [dbo].[Funcionario] ([Id]),
    CONSTRAINT [FK_FUNACION_REFERENCE_SERVICO] FOREIGN KEY ([ServicoId]) REFERENCES [dbo].[Servico] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [ASSOCIATION_2_FK]
    ON [dbo].[FuncionarioServico]([FuncionarioId] ASC);

