CREATE TABLE [dbo].[FuncionarioTipoPet] (
    [FuncionarioId] UNIQUEIDENTIFIER NOT NULL,
    [TipoPetId]     int NOT NULL,
    CONSTRAINT [PK_FUNCIONARIOTIPOPET] PRIMARY KEY CLUSTERED ([FuncionarioId] ASC, [TipoPetId] ASC),
    CONSTRAINT [FK_FUNCIONA_ASSOCIATI_FUNCINAR] FOREIGN KEY ([FuncionarioId]) REFERENCES [dbo].[Funcionario] ([Id]),
    CONSTRAINT [FK_FUNCIONA_ASSOCIATI_TIPOPET] FOREIGN KEY ([TipoPetId]) REFERENCES [dbo].[TipoPet] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [ASSOCIATION_4_FK]
    ON [dbo].[FuncionarioTipoPet]([FuncionarioId] ASC);

