CREATE TABLE [dbo].[Raca] (
    [Id]   INT    IDENTITY(1,1)       NOT NULL,
    [Nome] VARCHAR (100) NOT NULL,
    [TipoPetId] INT NOT NULL, 
    CONSTRAINT [PK_RACA] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TIPO_PET_RACA] FOREIGN KEY (TipoPetId) REFERENCES [dbo].TipoPet (Id)
);

